version: '3.5'

services:
  postgres:
    container_name: book-dressing-pg
    image: postgres:12.6-alpine
    environment:
      POSTGRES_DB: ${SQL_DATABASE}
      POSTGRES_USER: ${SQL_USERNAME}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - ${SQL_PORT}:5432
    networks:
      - book-dressing-network
    restart: unless-stopped


networks:
  book-dressing-network:
    driver: bridge

volumes:
    postgres:
